version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update the VARIANT arg to pick a version of Go: 1, 1.16, 1.15
        "VARIANT": "1.19-bullseye"
        # Options
        "INSTALL_NODE": "false"
        "NODE_VERSION": "lts/*"
    container_name: gedo_mazo_app
    volumes:
    - ..:/workspaces/gedo_mazo:cached
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mongo:latest
    container_name: gedo_mazo_db
    restart: unless-stopped
    volumes:
    - gedo_mazo-mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: gedo_mazo_usr
      MONGO_INITDB_ROOT_PASSWORD: gedo_mazo_pass
      MONGO_INITDB_DATABASE: gedo_mazo_db

volumes:
  gedo_mazo-mongodb-data:
